### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by jasongitmail** [ocluf/justship#11]
Really cool to see more indie devs using Svelte!

For SEO, it's missing a sitemap

I might suggest Super Sitemap: https://github.com/jasongitmail/super-sitemap (I'm the author & searched deeply for a good one before building this.)

If you add it, remember to update `excludeRoutePatterns` in the config to add regex's for your stripe callback dir and auth routes, so those are excluded from your sitemap paths (see README). 

Cheers!

**Comment by ocluf** [comment]
This looks great will add.

**Comment by jasongitmail** [comment]
unpushed?

**Comment by ocluf** [comment]
oops yeah unpushed live now
