### ISSUE TITLE
Twitter metatadata

### ISSUE THREAD

**Issue by jasongitmail** [ocluf/justship#13]
Just a tip

Twitter uses (falls back to) OG's url, title, description, & image tags. So if you wanted to, you [could remove `twitter:title` and `twitter:description`](https://github.com/ocluf/justship/blob/main/src/routes/%2Blayout.svelte#L18-L27) to clean it up, unless you plan to ever specify those differently.
https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

**Comment by ocluf** [comment]
Done, I copied the solution for meta tags you posted in another issue. Going to add the sitemap this week as well. Suggestions have been great so far any other features that you think could make this boilerplate more awesome?

**Comment by jasongitmail** [comment]
You could add a basic Content Security Policy to svelte.config.js.

IMO fleshing out subscription handling: table, model, check status during sign in, etc would be very useful for people.

**Comment by ocluf** [comment]
Yeah that seems fair. Need to make a SaaS first that is serious enough to warrant a subscription . Only made things with one-time-payments so far
