### ISSUE TITLE
Bug: SEO

### ISSUE THREAD

**Issue by jasongitmail** [ocluf/justship#14]
https://github.com/ocluf/justship/blob/f22964a096e10ccc2be7e181b39673cd46190454/src/routes/privacy-policy/%2Blayout.ts#L9

needs to be `return seo` in order to overwrite the default SEO properties

**Comment by ocluf** [comment]
Fixed thanks! For now changed it to `return seo` I think it might make more sense in the future to have a single seo object in the load function instead of all properties separate.

**Comment by jasongitmail** [comment]
Yeah, that's how I do mine. It feels organized and prevents possibility of collisions with the route's data. 

```ts
import type { Meta } from "$lib/meta";

export async function load() {
  const meta: Meta = {
    title: "Support",
    description: "Have questions? Get in touch.",
  };

  return { meta };
}
```

I also ultimately removed the default properties object from `layout.ts` and ended up using a function within `+layout.svelte` like this:
```ts
const meta = $derived.by(() =>
  getMeta({
    siteName: PUBLIC_SITE_NAME,
    defaultTitle: PUBLIC_DEFAULT_TITLE,
    defaultDescription: PUBLIC_DEFAULT_DESCRIPTION,
    defaultOGImage,
    routeMeta: $page.data?.meta ?? {},
    url: $page.url,
    pageParam: $page.params?.page ?? "",
  }),
);
```

I tried to avoid this approach at first because it seems less "proper", but given that logic needs to occur after route metadata is specified (e.g. "use ogDescription if exists, else the meta description, else defaultDescription"; or page title formatting), it's the best solution I've found given it's more testable than littering my layout with ternaries.

Then I use the result like:
```svelte
...
  <meta property="og:type" content={meta.ogType} />
  <meta property="og:title" content={meta.ogTitle} />
  <meta property="og:description" content={meta.ogDescription} />
  <meta property="og:image" content={meta.ogImage} />
  <meta property="og:url" content={meta.ogUrl} />
  ...
```

If I get to doing a full write up on it, I'll link it here.

**Comment by jasongitmail** [comment]
@ocluf I just posted a full write up on my SEO strategy including code too, in case helpful as a reference. Feel free to use whatever. https://github.com/jasongitmail/sveltekit-extended-docs/blob/main/SEO/SEO.md#seo-metadata

**Comment by ocluf** [comment]
Yeah it this is probably the best way to do it now, thanks!
