### ISSUE TITLE
Lucia deprecation thoughts

### ISSUE THREAD

**Issue by allanalvaro** [ocluf/justship#17]
Hello,
 This is more for an opinion and information to understand if there is any plan to do anything with the Lucia implementation since the maintainer announced that the lib will be deprecated in favor of using it as a source learning tool.

**Comment by ocluf** [comment]
I'd be open to alternatives. The current version works for me though

**Comment by allanalvaro** [comment]
I don't have an alternative yet. Since I'm going to start using justship, I came cross this announcement and I was wondering if you had anything in mind to change or not.
Honestly, I don't know if this will impact or affect the ability to keep up with the updates after depreciation.
