### ISSUE TITLE
embla-carousel-svelte@8.1.5 conflicts with svelte@5.0.0-next.158

### ISSUE THREAD

**Issue by rajivpoddar** [ocluf/justship#5]
```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: justship2@0.0.1
npm error Found: svelte@5.0.0-next.158
npm error node_modules/svelte
npm error   dev svelte@"^5.0.0-next.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^3.49.0 || ^4.0.0" from embla-carousel-svelte@8.1.5
npm error node_modules/embla-carousel-svelte
npm error   embla-carousel-svelte@"^8.1.3" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/rajiv/.npm/_logs/2024-06-19T05_58_01_485Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/rajiv/.npm/_logs/2024-06-19T05_58_01_485Z-debug-0.log
```

**Comment by ocluf** [comment]
Hey rajiv, 

Yes it seems the embla-carousel package doesn't officially support svelte 5 yet even though it seems to work fine. I normally use pnpm where you'll just get a warning. 

You can either:

- use npm with --force or --legacy-peer-deps
- use pnpm (basically npm but way quicker)
- remove the feature carousel component and the embla carousel dependency as that is the only place it gets used. 

Will leave this issue open with that solution until official svelte 5 support drops for the package.

**Comment by davidjerleke** [comment]
@rajivpoddar, @ocluf, I would happily accept a PR to make `embla-carousel` compatible with Svelte  v5 and up. Please see the following discussion for details:

- https://github.com/davidjerleke/embla-carousel/discussions/796
