### ISSUE TITLE
proposition: Use bun

### ISSUE THREAD

**Issue by Creative-Difficulty** [ocluf/justship#7]
This might seem like I'm trying to force my package manager/runtime etc. of choice on this project, but please hear me out:
1) Bun is *significantly* faster than both pnpm and npm (and yarn)
2) Bun is is significantly faster than node
3) it has become a stable and reliable runtime with windows support in v1.1

For these (and many more) reasons i'd like to propose the use of bun as the package manager and runtime for this project.

**Comment by ocluf** [comment]
hey @Creative-Difficulty, 

Thank you for contributing! I hope to see more of that. 

I've heard good things about bun but does this require any code changes? Isn't it just a matter of running `bun install` instead of `pnpm install` and switching out the auto-adapter with the one from bun.

**Comment by Creative-Difficulty** [comment]
No this change does not require any code changes. It's just a matter of replacing the lockfiles and (as you said) switching out the adapter. However this is in my opinion a great move for better perfomance and the project being at the bleeding edge (but still stable 😎)

Thank you, I'm looking forward to contributing!

**Comment by Creative-Difficulty** [comment]
@ocluf

**Comment by ocluf** [comment]
I like bun but this template has been designed with Vercel in mind (It uses vercel rewrites as a reverse proxy so that calls made to Posthog don't get blocked by adblockers). 

Vercel only seems to have node runtimes so I'd rather use the same runtime locally to keep the local and production environment as similar as possible. For me pnpm is also quick enough. Maybe if Vercel adds bun runtime as an option I'll consider it, but for now closing this issue

**Comment by Creative-Difficulty** [comment]
bun install is already supported https://vercel.com/changelog/bun-install-is-now-supported-with-zero-configuration
Please dont close, this is not completed!

**Comment by Creative-Difficulty** [comment]
@ocluf

**Comment by ocluf** [comment]
Bun install is something different than the bun runtime. You can install the dependencies with the bun file but your code will still be run by node.

**Comment by jasongitmail** [comment]
+1 for Bun. Both Vercel and Cloudflare Pages support bun for package management, even though their runtimes are not Bun. Great experience as a package manager and big time saver

**Comment by Creative-Difficulty** [comment]
@ocluf

**Comment by ocluf** [comment]
Hey @jasongitmail, With timesaver do you mean simply the amount of time saved when running bun install or is their something else I'm missing?
